---
version: 2
PvpDamageNerf: 0.85  # Nerf Damage % or ^ (Depends on which formula used) (PVP)
PvpDefenseNerf: 0.825  # Nerf Defense % or ^ (Depends on which formula used) (PVP)
aat: 150 
paat: 150 
tbaf: 300.0
bppr: 15
MaxWallJumpDistance: 0.8
PenaltyPerRebirth: 0.35