version: 4
admin_team:
  chat:
    text_color: red
    icon_set: skill_iconset
    index: 331
  members:
    - admin
    - alkanov
    - zelp
    - mod1
    - uragus
mod_team:
  chat:
    text_color: "#ff8000"
    icon_set: skill_iconset
    index: 101
  members:
    - alkanov
tutor_team:
  chat:
    text_color: "#e6cc80"
    icon_set: skill_iconset
    index: 109
  members:
    - alkanov
